import Vue from 'vue';
import AutoComplete from 'primevue/components/autocomplete/AutoComplete.vue';
import Accordion from 'primevue/components/accordion/Accordion.vue';
import AccordionTab from 'primevue/components/accordiontab/AccordionTab.vue';
import BlockUI from 'primevue/components/blockui/BlockUI.vue';
import Button from 'primevue/components/button/Button.vue';
import Breadcrumb from 'primevue/components/breadcrumb/Breadcrumb.vue';
import Calendar from 'primevue/components/calendar/Calendar.vue';
import Card from 'primevue/components/card/Card.vue';
import Carousel from 'primevue/components/carousel/Carousel.vue';
import Chart from 'primevue/components/chart/Chart.vue';
import Checkbox from 'primevue/components/checkbox/Checkbox.vue';
import Chips from 'primevue/components/chips/Chips.vue';
import ColorPicker from 'primevue/components/colorpicker/ColorPicker.vue';
import Column from 'primevue/components/column/Column.vue';
import ContextMenu from 'primevue/components/contextmenu/ContextMenu.vue';
import DataTable from 'primevue/components/datatable/DataTable.vue';
import DataView from 'primevue/components/dataview/DataView.vue';
import DataViewLayoutOptions from 'primevue/components/dataviewlayoutoptions/DataViewLayoutOptions.vue';
import Dialog from 'primevue/components/dialog/Dialog.vue';
import Dropdown from 'primevue/components/dropdown/Dropdown.vue';
// import Editor from 'primevue/components/editor/Editor.vue';
import Fieldset from 'primevue/components/fieldset/Fieldset.vue';
import FileUpload from 'primevue/components/fileupload/FileUpload.vue';
// import FullCalendar from 'primevue/components/fullcalendar/FullCalendar.vue';
import InlineMessage from 'primevue/components/inlinemessage/InlineMessage.vue';
import Inplace from 'primevue/components/inplace/Inplace.vue';
import InputMask from 'primevue/components/inputmask/InputMask.vue';
import InputNumber from 'primevue/components/inputnumber/InputNumber.vue';
import InputSwitch from 'primevue/components/inputswitch/InputSwitch.vue';
import InputText from 'primevue/components/inputtext/InputText.vue';
import Listbox from 'primevue/components/listbox/Listbox.vue';
import MegaMenu from 'primevue/components/megamenu/MegaMenu.vue';
import Menu from 'primevue/components/menu/Menu.vue';
import Menubar from 'primevue/components/menubar/Menubar.vue';
import Message from 'primevue/components/message/Message.vue';
import MultiSelect from 'primevue/components/multiselect/MultiSelect.vue';
import OrderList from 'primevue/components/orderlist/OrderList.vue';
import OrganizationChart from 'primevue/components/organizationchart/OrganizationChart.vue';
import OverlayPanel from 'primevue/components/overlaypanel/OverlayPanel.vue';
import Paginator from 'primevue/components/paginator/Paginator.vue';
import Panel from 'primevue/components/panel/Panel.vue';
import PanelMenu from 'primevue/components/panelmenu/PanelMenu.vue';
import Password from 'primevue/components/password/Password.vue';
import PickList from 'primevue/components/picklist/PickList.vue';
import ProgressBar from 'primevue/components/progressbar/ProgressBar.vue';
import ProgressSpinner from 'primevue/components/progressspinner/ProgressSpinner.vue';
import Rating from 'primevue/components/rating/Rating.vue';
import RadioButton from 'primevue/components/radiobutton/RadioButton.vue';
import Ripple from 'primevue/ripple.js';
import SelectButton from 'primevue/components/selectbutton/SelectButton.vue';
import Slider from 'primevue/components/slider/Slider.vue';
import Sidebar from 'primevue/components/sidebar/Sidebar.vue';
import SplitButton from 'primevue/components/splitbutton/SplitButton.vue';
import Steps from 'primevue/components/steps/Steps.vue';
import TabMenu from 'primevue/components/tabmenu/TabMenu.vue';
import TieredMenu from 'primevue/components/tieredmenu/TieredMenu.vue';
import Textarea from 'primevue/components/textarea/Textarea.vue';
import Toast from 'primevue/components/toast/Toast.vue';
import ToastService from 'primevue/toastservice';
import Toolbar from 'primevue/components/toolbar/Toolbar.vue';
import TabView from 'primevue/components/tabview/TabView.vue';
import TabPanel from 'primevue/components/tabpanel/TabPanel.vue';
import Tooltip from 'primevue/tooltip.js';
import ToggleButton from 'primevue/components/togglebutton/ToggleButton.vue';
import Tree from 'primevue/components/tree/Tree.vue';
import TreeTable from 'primevue/components/treetable/TreeTable.vue';
import TriStateCheckbox from 'primevue/components/tristatecheckbox/TriStateCheckbox.vue';

Vue.use(ToastService);

Vue.component('Accordion', Accordion);
Vue.component('AccordionTab', AccordionTab);
Vue.component('AutoComplete', AutoComplete);
Vue.component('BlockUI', BlockUI);
Vue.component('Breadcrumb', Breadcrumb);
Vue.component('Button', Button);
Vue.component('Calendar', Calendar);
Vue.component('Card', Card);
Vue.component('Carousel', Carousel);
Vue.component('Chart', Chart);
Vue.component('Checkbox', Checkbox);
Vue.component('Chips', Chips);
Vue.component('ColorPicker', ColorPicker);
Vue.component('Column', Column);
Vue.component('ContextMenu', ContextMenu);
Vue.component('DataTable', DataTable);
Vue.component('DataView', DataView);
Vue.component('DataViewLayoutOptions', DataViewLayoutOptions);
Vue.component('Dialog', Dialog);
Vue.component('Dropdown', Dropdown);
// Vue.component('Editor', Editor);
Vue.component('Fieldset', Fieldset);
Vue.component('FileUpload', FileUpload);
// Vue.component('FullCalendar', FullCalendar);
Vue.component('InlineMessage', InlineMessage);
Vue.component('Inplace', Inplace);
Vue.component('InputMask', InputMask);
Vue.component('InputNumber', InputNumber);
Vue.component('InputSwitch', InputSwitch);
Vue.component('InputText', InputText);
Vue.component('Listbox', Listbox);
Vue.component('MegaMenu', MegaMenu);
Vue.component('Menu', Menu);
Vue.component('Menubar', Menubar);
Vue.component('Message', Message);
Vue.component('MultiSelect', MultiSelect);
Vue.component('OrderList', OrderList);
Vue.component('OrganizationChart', OrganizationChart);
Vue.component('OverlayPanel', OverlayPanel);
Vue.component('Paginator', Paginator);
Vue.component('Panel', Panel);
Vue.component('PanelMenu', PanelMenu);
Vue.component('Password', Password);
Vue.component('PickList', PickList);
Vue.component('ProgressBar', ProgressBar);
Vue.component('ProgressSpinner', ProgressSpinner);
Vue.component('RadioButton', RadioButton);
Vue.component('Rating', Rating);
Vue.component('SelectButton', SelectButton);
Vue.component('Slider', Slider);
Vue.component('Sidebar', Sidebar);
Vue.component('SplitButton', SplitButton);
Vue.component('Steps', Steps);
Vue.component('TabMenu', TabMenu);
Vue.component('TabView', TabView);
Vue.component('TabPanel', TabPanel);
Vue.component('Textarea', Textarea);
Vue.component('TieredMenu', TieredMenu);
Vue.component('Toast', Toast);
Vue.component('Toolbar', Toolbar);
Vue.component('ToggleButton', ToggleButton);
Vue.component('Tree', Tree);
Vue.component('TreeTable', TreeTable);
Vue.component('TriStateCheckbox', TriStateCheckbox);